#!/usr/bin/env bash
# Configures Nginx server to have a custom 404 page that contains
#  the string `Ceci n'est pas une page`.
apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/404_page.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404_page.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://google.com/doodles/;
    }

    error_page 404 /404_page.html;
    location /404_page {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
