#!/usr/bin/env bash
# Displays "Best School" 10 times using a `while` loop.
# For the 9th iteration, it displays "Best School" and then "Hi" on a new line.
count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
